### ISSUE TITLE
Add support for parsing something else than an external file

### ISSUE THREAD

**Issue by wrmbaron** [paulelsner/gurkenlaeufer#18]
Feature file can only be read from files on a filesystem, as the parameter is interpreted as a file name. In testing, I may not wish to have a dependency on a filesystem, as I need to read from a literal, a network connection or whatever else. Also, providing the file content in the build or install environment may be a pain.
There should be an alternative to `gurkenlaeufer::Parser::parseFile(const std::string&)` like `gurkenlaeufer::Parser::parseString(const std::string&)` or `gurkenlaeufer::Parser::parseStream(std::istream*)`
- the implementation is trivial, only some extraction code is needed
- the variants without the file name can only report on a generic error or need an extra name parameter

**Comment by paulelsner** [comment]
Hi @wrmbaron, the interface you are searching already exists: 
`Parser::parseLine`
which is exactly for this use-case.
Since the implementation is header only, you can also simply use your own parser.

Let me know if you need more.

**Comment by wrmbaron** [comment]
Unfortunately, `Parser::parseLine()` only does what is says. The multi line handling is not part of it. Using only `Parser::parseLine()` would force me to re-implement 90% of `Parser::parseFile()`. Keeping one one implementation for all needs would greatly help the community, especially when the change is so small.
The `parseFile()` function really works on `std::istream` most of the time already, so separating that as suggested would clean up the code and make the functionality available for a wider range of use cases. I am willing to supply an implementation for that.

**Comment by paulelsner** [comment]
Now I see your point, thanks for clarification.
Is this how it could work for you? https://github.com/paulelsner/gurkenlaeufer/pull/19

**Comment by wrmbaron** [comment]
Brilliant, thank you very much!

_Sidenote: I would never use non const reference parameters, as it hides the fact, that the original variable can be changed from the calling code, but that's just my personal taste._

I like your project very much. It makes testing so much easier to manage.

**Comment by paulelsner** [comment]
Im with you on the const-ref. In this case it is not possible, since std::getline modifies the stream. And I don't like copies ;)
Nice that you like the project. Actually you are the first one I heared of using it outside my work environment.

**Comment by wrmbaron** [comment]
Oh, I hope that won't stay like that and you already have a downloadable package on conancenter (which is where I found gurkenlaeufer in the first place).

Concerning the reference parameter, that is not quite so. You can always write the writable reference as a pointer. It is, what happens behind the scenes anyway. Using the converted parameter just needs an asterisk to dereference the pointer, from which the next function takes the address, which is perfectly all right. So the code could just as well be:

```c++
    void parseFile(const std::string& filePath)
    {
        std::ifstream fin(filePath);
        if (fin.fail()) {
            throw std::invalid_argument("The given cucumber feature file '" + filePath + "' can not be opened!");
        }
        parseStream(&fin);
    }

    void parseStream(std::istream* stream)
    {
        for (std::string line; std::getline(*stream, line);) {
            std::cout << line << std::endl;

        ...
        }
    }
```

Now you can see, that the call to `parseStream()` may change `fin`.

**Comment by paulelsner** [comment]
I see, making it more visible to the caller that the parameter might get changed. Totally agree an usually I do it this way. Bad Stackoverflow influence ;)

Seems one of my colleagues put it on conancenter.

**Comment by paulelsner** [comment]
solved with https://github.com/paulelsner/gurkenlaeufer/pull/19

**Comment by wrmbaron** [comment]
Wow, that was super fast, now I only have to wait for a new release on conancenter or roll my own package. Thanks a lot, you are very helpful!

**Comment by paulelsner** [comment]
https://github.com/conan-io/conan-center-index/pull/18038
new version should be available soon.
